### ISSUE TITLE
What does yellow mean?

### ISSUE THREAD

**Issue by daniel-brenot** [fasterthanlime/pegviz#3]
I see some things match and then show as yellow and don't consume the stream. You don't indicate what yellow is supposed to mean in the readme. Can you please update the readme to explain it?

**Comment by kopp** [comment]
In the css I found

```css
span.success {
    border-color: #27966d;
}
span.failure {
    border-color: #942c2c;
    text-decoration: line-through;
}
span.failure.partial-match {
    border-color: #ba8925;  // YELLOW
    text-decoration: initial;
}
```

and in the code the 'definition':

```rust
fn mark_partial_matches(node: &mut Node) -> bool {
    for c in &mut node.children {
        mark_partial_matches(c);
    }

    let ret = (matches!(node.state, State::Success) && !node.rule.is_zero_len())
        || node.children.iter().any(|c| c.partial_match);
    node.partial_match = ret;
    ret
}
```

which I honestly do not fully understand.

From looking at visualizations it appears that yellow/partial match means, that a first part of the rule did match, but a second part did not (e.g. because both rules share the same prefix).

@fasterthanlime : Is that the correct way to understand it?
